<?php
$form = $this->form;
$statistics = $this->statistics;

$form->get('content')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Type content here',
    'rows' => 6
]);

$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);
$form->prepare();

?>

<h1>Analyze Text</h1>

<p>
    Please fill out the following field and click the <i>Analyze</i> button.
</p>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>

        <div class="form-group">
            <?= $this->formLabel($form->get('content')); ?>
            <?= $this->formElement($form->get('content')); ?>
            <?= $this->formElementErrors($form->get('content')); ?>
        </div>

        <?= $this->formElement($form->get('submit')); ?>

        <?= $this->form()->closeTag(); ?>
    </div>

    <?php if (!empty($statistics)): ?>
        <div class="col-md-6">
            <table id="graph-table" class="table table-bordered">
                <thead>
                <tr>
                    <th>Character</th>
                    <th>Qty</th>
                    <th>Before</th>
                    <th>After</th>
                    <th>Longest Distance</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($statistics as $row): ?>
                    <tr>
                        <td><?= $row['char'] ?></td>
                        <td><?= $row['qty'] ?></td>
                        <td><?= $row['before'] ?></td>
                        <td><?= $row['after'] ?></td>
                        <td><?= $row['max'] ?></td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    <?php endif; ?>
</div>